#!/bin/bash
# vim:ft=sh:
#http://www.funtoo.org/wiki/Keychain

if [ ! -x "`which keychain 2> /dev/null`" ] ; then
	return
fi

unset SSH_ASKPASS
eval `keychain --quick --eval --ignore-missing --noask --agents ssh,gpg --inherit any $GPG_KEY_ID`
